In [ ]:
#print a number pattern using a for loop and range function
#Take Levels from user 
levels = int(input('Enter number of levels:'))
for level in range(1,levels+1):
    for num in range(level):
        print(Level,end="")#print number
        #new line

In [7]:
# declare a string 
text ="I Love Python"

In [8]:
#get only the first element
#indexing starts from 0 in python
text[0]

'I'

In [9]:
#display all the elements of the string variable
text[:]

'I Love Python'

In [4]:
#display all the elements using len()
#len() functions give length of the varialbe
text[:len(text)]

'I Love Python'

In [10]:
#display the first three letters alone by specifying the start and the end 
#indexting starts from 0 in python and ends at n-1
text[0:6]

'I Love'

In [6]:
text[2:]

'Love Python'

In [7]:
text[7:13]

'Python'

In [12]:
text[1:-2]

' Love Pyth'

In [14]:
text[::-1]

'nohtyP evoL I'

In [15]:
text[::-1][-3]

'L'

In [18]:
text.replace("Python","Data Science")

'I Love Data Science'

In [19]:
text.upper()

'I LOVE PYTHON'

In [20]:
text.lower()

'i love python'

In [21]:
text.title()

'I Love Python'

In [23]:
#Concentrate each element of data with sep
date="08","03","2020"
sep='_'
sep.join(date)

'08_03_2020'

In [ ]:
#Print the string by removing leading and trailing "*" character 
text="*** Python"

In [25]:
#Creating a list""
book_list = ["Data Science with Python","into the machine learning","Big Data-Hadoop"]
print(book_list)
type(book_list)

['Data Science with Python', 'into the machine learning', 'Big Data-Hadoop']


list

In [26]:
x=[2.3,'Cereals',"USA",3,"China",3.5]

In [27]:
x.sort()

TypeError: '<' not supported between instances of 'str' and 'float'

In [29]:
avg_prices=[2,63,85,66,63]
avg_prices.sort(reverse=True)
Print('sorted list(in descending):',avg_prices)

NameError: name 'Print' is not defined

In [30]:
print(63 in avg_prices)

True


In [31]:
print(66 not in avg_prices)

False


In [11]:
x=[1,2,58,74,69]
x

[1, 2, 58, 74, 69]

In [12]:
x=[1,2,58,74,69]
y=sorted(x)
y

[1, 2, 58, 69, 74]

In [13]:
y.sort(reverse= True)
y

[74, 69, 58, 2, 1]

In [16]:
print(1 in x)

True


In [21]:
print(69 not in x)

False


In [22]:
len(x)

5

In [23]:
max(x)

74

In [24]:
min(x)

1

In [26]:
x.clear()
x

[]

In [14]:
u=[56,45,85,76]
x

[1, 2, 58, 74, 69]

In [15]:
z=u.copy()
z

[56, 45, 85, 76]

In [16]:
z.append(5)
z

[56, 45, 85, 76, 5]

In [17]:
z.append(56)
z

[56, 45, 85, 76, 5, 56]

In [18]:
z.count(56)

2

In [23]:
print(z[1:3])

[45, 85]


In [29]:
print(z[-4:-2])

[85, 76]


In [30]:
books={"te":3,"fg":67}

In [31]:
books["gh"]=54

In [32]:
books

{'te': 3, 'fg': 67, 'gh': 54}

In [33]:
del books["gh"]

In [34]:
books

{'te': 3, 'fg': 67}

In [43]:
twit = "can you can a you can a"
twit

'can you can a you can a'

In [36]:
word_count={}

In [45]:
for word in twit.split():
    if word not in word_count:
        word_count[word] =1
    else: 
        word_count[word] +=1
print(word_count)

{'can': 3, 'you': 2, 'a': 2}


# List Comprehension

In [3]:
#using series using simple for loop
series_num=[]
for i in range(1,11):
    series_num.append(i*i)
print(series_num)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [4]:
#using list comprehensions
sq_num_series=[i*i for i in range(1,11)]
print(sq_num_series)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [7]:
#Creating a list
products=["avv","bds","cds"]
#get the first letter of each element
f_l=[v[0] for v in products]
f_l

['a', 'b', 'c']

In [19]:
#extract all the numbers from the string
text = 'ha jasj adka 500 bhakjhf 400'
numbers = [int(i) for i in text.split() if i.isdigit() == True]
print(numbers)

[500, 400]


In [17]:
# extract vowels from the string
sentence = "I will steer mu boat, I will find my way"
vowels=[vowel for vowel in sentence if vowel in 'aeiouAEIOU']
vowels

['I', 'i', 'e', 'e', 'u', 'o', 'a', 'I', 'i', 'i', 'a']

In [20]:
#using nested conditional statements in the comprehension
products = ["coke","cookies","apple"]
discounts=[10 if p == "coke" else 20 if p == "cookies" else 30 for p in products]
discounts

[10, 20, 30]

In [ ]:
#Q:- Find string in a list that are longer than 9 charcter using list comprehension


# Functions

In [6]:
def greet():
    print("hello welcome to imarticus")

In [7]:
greet()

hello welcome to imarticus


In [8]:
def addition(n1,n2):
    add = n1+n2
    return(add)

In [9]:
sum=addition(5,9)
sum

14

In [2]:
def greet():
    print("hello and welcome to our world")

In [1]:
person_name= input("enter your name")

enter your namejohn


In [10]:
def hello(name):
    print("hello"+ name +"have a good day")

In [3]:
hello()

TypeError: hello() missing 1 required positional argument: 'name'

In [11]:
hello("john")

hellojohnhave a good day


In [20]:
#how to change order yet get correct values
def employee(name,designations):
    print(name,designation)

In [21]:
employee(name="saif",designations="director")
employee(designations="director", name="saif")

NameError: name 'designation' is not defined

In [22]:
def emp(name,sal=1200):
    print("emp name:", name)
    print("emp salary:", sal)
emp("sam")

emp name: sam
emp salary: 1200


In [26]:
#variable lenghth arguments
def addition1(*numbers):
    add1=0
    for num1 in numbers:
        add1=add1+num1
        print(add1)

In [27]:
addition1(5,6)

5
11


In [29]:
addition1(58,66,45)

58
124
169


In [32]:
#do the above equation from list comprehention

In [ ]:
def employee(**details):
    print(type(details))
    for k,v in details.items():
        print(k,"-->",v)

# Lambda function

In [2]:
def greater(n1,n2):
    if (n1>n2):
        return n1
    else:
        return n2

In [3]:
great= greater(5,12)
great

12

In [4]:
greater=lambda n1,n2 :n1 if n1>n2 else n2
greater(4,45)

45

In [1]:
num_list = list(range(1,11))
sq_list=list(map(lambda x:(x+2,x**2),num_list))
sq_list

[(3, 1),
 (4, 4),
 (5, 9),
 (6, 16),
 (7, 25),
 (8, 36),
 (9, 49),
 (10, 64),
 (11, 81),
 (12, 100)]

In [2]:
lst = range(1,11)
lst2 = list(map(lambda x:(x+2,x**3), lst))

a = [ i for i,j in lst2]

b = [ j for i,j in lst2]

print ('Sum list is :', a) 
print ('Cube list is :', b)

Sum list is : [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Cube list is : [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [3]:
num_list=list(range(1,11))
sq_list = list(filter(lambda x: x%5 == 0, num_list))
sq_list

[5, 10]

In [7]:
num_list=list(range(1,100))
sq_list = list(filter(lambda x: (x%15 ) == 0, num_list))
sq_list

[15, 30, 45, 60, 75, 90]

In [10]:
num_list=list(range(1,100))
sq_list = list(filter(lambda x: (x%3==0) & (x%5==0), num_list))
sq_list

[15, 30, 45, 60, 75, 90]

In [6]:
# lambda with reduce
from functools import reduce
num_list=[1,2,3,4]
reduce(lambda a,b:a*b,num_list)

24

# Numpy

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [4]:
#declaring a list
age_list=[25,46,45,41]

In [5]:
#creating array from the list using np.array
age_array=np.array(age_list)

In [6]:
age_array

array([25, 46, 45, 41])

In [7]:
type(age_array)

numpy.ndarray

In [11]:
# create a numpy array 
books = np.array (["lp","ds","sc"])

In [9]:
type(books)

numpy.ndarray

In [12]:
books

array(['lp', 'ds', 'sc'], dtype='<U2')

In [13]:
#create an array of 20 random number using random() method from random module
np.random.random(size=20)

array([0.98159029, 0.88840964, 0.00649147, 0.48141644, 0.97849114,
       0.19549762, 0.26844308, 0.45390606, 0.40263454, 0.29729148,
       0.93112033, 0.51300784, 0.20315714, 0.72191948, 0.1113707 ,
       0.89470911, 0.92058999, 0.36164211, 0.58342112, 0.42804039])

In [14]:
np.random.rand(2,6)

array([[0.81796959, 0.02173526, 0.87902935, 0.8631451 , 0.11309434,
        0.43147777],
       [0.24057659, 0.06946514, 0.32709561, 0.21304962, 0.14924459,
        0.93294423]])

In [18]:
np.random.randint(2,10)

8

In [19]:
np.random.randint(10,100,10)

array([10, 44, 45, 31, 38, 25, 51, 64, 44, 56])

In [22]:
# creating an array of even number between 10 and 100
# Here 10 is inclusive and 100 is exclusive
evn_nums = np.arange(start =10, stop=100,step=2)

In [23]:
evn_nums

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
type(evn_nums)

numpy.ndarray

In [29]:
nums = np.linspace(start =1, stop=100,num=10)

In [30]:
nums

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [31]:
# creating 1D numpy array of Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
#creating 1D numpy array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
#creating a 3x3 matrix with arbitray values
matrix=np.empty((3,3),dtype=int)
matrix

array([[   0,    0,    0],
       [   0,    0,    0],
       [1344,    0,    0]])

In [34]:
matrix=np.full((3,3),fill_value=11)
matrix

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
# k= for diagonal, N = num of row, M= num of column 
np.eye(N=4, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.eye(N=4, M=5, k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [38]:
np.eye(N=4, M=5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [41]:
#creating a numpy array
books = np.array([(25,45,63),("lp","ds","sc")])
books

array([['25', '45', '63'],
       ['lp', 'ds', 'sc']], dtype='<U11')

In [42]:
print("shape of the array is:",books.shape)

shape of the array is: (2, 3)


In [ ]:
#indexing an array
data scientists=np.array

In [43]:
#slicing the array

#consider a 1D array
weight=np.array([14,56,54,48,19,78])

In [44]:
print("4th and 5th element:", weight[3:5])

4th and 5th element: [48 19]


In [46]:
print("every third element:", weight[0::3])

every third element: [14 48]


In [48]:
print("element before 19",weight[:4])

element before 19 [14 56 54 48]


In [5]:
age=np.array([(54,64,85),(78,55,95)])
#54,64,85
#78,55,95

In [6]:
#[1,2;3]  where 1 & 2 is row & column 
print(age[0,0:2])

[54 64]


# Numpy array operation

In [62]:
m1=np.array([[1,0,2],[4,5,9]])

In [63]:
m2=np.array([[4,5,8],[7,6,9]])

In [64]:
m1

array([[1, 0, 2],
       [4, 5, 9]])

In [65]:
m2

array([[4, 5, 8],
       [7, 6, 9]])

In [67]:
prod=m1*m2

In [68]:
prod # this prod is konown as "hadamard product"

array([[ 4,  0, 16],
       [28, 30, 81]])

In [75]:
m4=np.array([[1,0,2],[4,5,9]])
m5=np.array([[4,5],[7,6],[1,4]])

In [76]:
multi= m4.dot(m5)
multi

array([[ 6, 13],
       [60, 86]])

In [77]:
salary=np.array([154545,2155411,6561231,41100])

In [78]:
salary.min() #return to minimum of array

41100

In [79]:
salary.max() #return to maximum of array

6561231

In [80]:
salary.var() #return to variance of array

6965976822178.6875

In [81]:
salary.std() #return to standard of array

2639313.702874042

In [82]:
#retuning the square
sq_side = np.array([25,26,45,35,85])

In [83]:
np.square(sq_side)

array([ 625,  676, 2025, 1225, 7225], dtype=int32)

In [84]:
#retuning the cube
cube_side=np.array([5,6,7,])

In [86]:
np.power(cube_side,3)

array([125, 216, 343], dtype=int32)

In [88]:
#transposing the matrix or side of the array
books = np.array([(25,45,63),("lp","ds","sc")])
books

array([['25', '45', '63'],
       ['lp', 'ds', 'sc']], dtype='<U11')

In [89]:
print(np.transpose(books))

[['25' 'lp']
 ['45' 'ds']
 ['63' 'sc']]


In [104]:
#concatenate 1D array
age1=np.array([54,64,85,78,55,95])

In [105]:
weight1=np.array([54,85,48,96,12,15])

In [106]:
employee = np.concatenate([age1,weight1])

In [107]:
employee

array([54, 64, 85, 78, 55, 95, 54, 85, 48, 96, 12, 15])

In [ ]:
#flatten() function collapses the original array into a single dimension


In [108]:
#Iterating through the 1Darray
books = np.array([(25,45,63),("lp","ds","sc")])
print(books.ndim)

2


In [110]:
for i in books:
    print(i)

['25' '45' '63']
['lp' 'ds' 'sc']


In [111]:
for i in books:
    for j in i:
        print(j)

25
45
63
lp
ds
sc


In [7]:
#comparing list and array
import numpy
import time

In [8]:
#declare the size of arrays and lists
size=10000000

In [9]:
#create a list 
num_list1=range(size)
num_list2=range(size)

In [10]:
#list
initialtime=time.time()
resultant_list=[(a*b) for a,b in zip(num_list1,num_list2)]

In [11]:
#calculate execution time now
print("time taken by lists:",(time.time()-initialtime),"seconds")

time taken by lists: 80.26241827011108 seconds


In [12]:
#Now let us try with arrays
#create arrays
num_array1=np.arange(size)
num_array2=np.arange(size)

In [13]:
#numpy array
initialtime=time.time()
resultant_array=num_array1+num_array2

In [14]:
#calculate execution time 
print("time taken by arrays:",(time.time()-initialtime),"seconds")

time taken by arrays: 82.54463601112366 seconds


# Panda

In [1]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [9]:
# create series from dictionary
Prod_dic={"Dairy":2500,"soft drinks":4810,}

In [10]:
Prod_series= pd.Series(Prod_dic)
Prod_series

Dairy          2500
soft drinks    4810
dtype: int64

In [13]:
#creating simple array
emp_array=np.array(["A1","A2","B5","C5","C45","D54","G4"])

In [15]:
emp_id_series=pd.Series(emp_array)
emp_id_series[-2:]

5    D54
6     G4
dtype: object

In [18]:
class_dict={"X":["Maths","Science","English"],"Y":["Physics","chemistry"],"Z":["Social Science"]}

In [19]:
#Filtering the series
Student_series=pd.Series(np.array([45,12,48,76,87]),index=["sop","ema","mia","ki","wa"])

In [21]:
Student_series[Student_series>45]

mia    48
ki     76
wa     87
dtype: int32

In [22]:
#arithmetic operations
sales_array=np.array([1500,1500,8400])

In [23]:
sales_series=pd.Series(sales_array)
sales_series*2

0     3000
1     3000
2    16800
dtype: int32

#ranking a series

In [3]:
#ranking a series
score_array=np.array([121,25,48,45,65,45])
score_series=pd.Series(score_array)
score_series.rank()

0    6.0
1    1.0
2    4.0
3    2.5
4    5.0
5    2.5
dtype: float64

In [4]:
#sorting the series in ascending order
sales_series=pd.Series([2245,4555,78745,4546,np.nan,5454,545,np.nan,5456])
sales_series.sort_values(ascending=True,na_position="last")

6      545.0
0     2245.0
3     4546.0
1     4555.0
5     5454.0
8     5456.0
2    78745.0
4        NaN
7        NaN
dtype: float64

In [6]:
#sorting the series in descending order
sales_series=pd.Series([2245,4555,78745,4546,np.nan,5454,545,np.nan,5456])
sales_series.sort_values(ascending=False,na_position="first")

4        NaN
7        NaN
2    78745.0
8     5456.0
5     5454.0
1     4555.0
3     4546.0
0     2245.0
6      545.0
dtype: float64

In [9]:
#sorting the index
sales_series=pd.Series(np.array([2245,4546,np.nan,5454,np.nan,5456]),index =[10,20,50,40,60,30])
sales_series
sales_series.sort_index(ascending=True)

10    2245.0
20    4546.0
30    5456.0
40    5454.0
50       NaN
60       NaN
dtype: float64

In [12]:
#checking null values
sales_series=pd.Series([2245,4555,78745,4546,np.nan,5454,545,np.nan,5456])
sales_series.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8    False
dtype: bool

In [13]:
sales_series.isna()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8    False
dtype: bool

In [15]:
sales_series.notnull()

0     True
1     True
2     True
3     True
4    False
5     True
6     True
7    False
8     True
dtype: bool

Concatenate a series

In [26]:
#Create series and concatenate them
class1=np.linspace(start=0,stop=20,num=11)
class2=np.linspace(start=0,stop=21,num=11)
class1_series=pd.Series(data=class1)
class2_series=pd.Series(data=class2)
#concatenating the series
pd.concat([class1_series,class2_series])

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
0      0.0
1      2.1
2      4.2
3      6.3
4      8.4
5     10.5
6     12.6
7     14.7
8     16.8
9     18.9
10    21.0
dtype: float64

In [25]:
pd.concat([class1_series,class2_series],
          keys=["Even","Odd"],
          names =["Category","Index"])

Category  Index
Even      0         0.0
          1         2.0
          2         4.0
          3         6.0
          4         8.0
          5        10.0
          6        12.0
          7        14.0
          8        16.0
          9        18.0
          10       20.0
Odd       0         0.0
          1         2.1
          2         4.2
          3         6.3
          4         8.4
          5        10.5
          6        12.6
          7        14.7
          8        16.8
          9        18.9
          10       21.0
dtype: float64

In [27]:
#concatenate the series using append
class1_series.append(class2_series)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
0      0.0
1      2.1
2      4.2
3      6.3
4      8.4
5     10.5
6     12.6
7     14.7
8     16.8
9     18.9
10    21.0
dtype: float64

In [28]:
#ignoring index follow it's own index
class1_series.append(class2_series,ignore_index=True)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11     0.0
12     2.1
13     4.2
14     6.3
15     8.4
16    10.5
17    12.6
18    14.7
19    16.8
20    18.9
21    21.0
dtype: float64